version: '2'
services:
  runner:
    image: sammousa/transip-rancher
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
    environment:
      WATCH_SERVICE: ${WATCH_SERVICE}
      USER_NAME: ${USER_NAME}
      PRIVATE_KEY: ${PRIVATE_KEY}