version: '2'
.catalog:
  name: "GitLab CI runner inside"
  version: "v0.0.1"
  description: "GitLab CI runners inside Rancher."
  questions:
    - variable: "CI_SERVER_URL"
      label: "GitLab URL"
      type: string
      required: true
    - variable: "REGISTRATION_TOKEN"
      label: "GitLab registration token"
      type: string
      required: true
    - variable: "CONCURRENT"
      label: "Concurrency"
      default: 1
      description: "See https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/configuration/advanced-configuration.md"
      type: string
      required: true
    - variable: "HOST_LABEL"
      label: Run on all hosts with this label
      default: "BUILD=1"
      type: string