version: '2'
.catalog:
  name: "Limesurvey 2.60"
  version: "2.67.2.170728-3"
  description: "Limesurvey 2.60 inside Rancher, using separate nginx / php-fpm containers."
  questions:
    - variable: "DBHOST"
      label: "Database host"
      type: string
      required: true
    - variable: "DBUSER"
      label: "Database user"
      type: string
      required: true
    - variable: "DBPASS"
      label: "Database password"
      type: string
      required: true
    - variable: "DBNAME"
      label: Database name
      type: string
      required: true