version: '2'
.catalog:
  name: "Limesurvey 2.60"
  version: "2.67.2.170728-5"
  description: "Limesurvey 2.60 inside Rancher, using separate nginx / php-fpm containers."
  questions:
    - variable: "DBHOST"
      label: "Database host"
      type: string
      required: true
    - variable: "DBUSER"
      label: "Database user"
      type: string
      required: true
    - variable: "DBPASS"
      label: "Database password"
      type: string
      required: true
    - variable: "DBNAME"
      label: Database name
      type: string
      required: true
services:
  php-fpm:
    upgrade_strategy:
      start_first: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      port: 9000
      interval: 2000
      unhealthy_treshold: 3
      strategy: recreate
  nginx:
    upgrade_strategy:
      start_first: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      port: 80
      interval: 2000
      unhealthy_treshold: 3
      strategy: recreate