version: '2'
services:
  php-fpm:
    image: sammousa/ls_phpfpm:2.67.2.170728-10
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBHOST: ${DBHOST}
      DBPASS: ${DBPASS}
    volumes_from:
      - ls-data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: ls-data
  nginx:
    image: sammousa/ls_nginx:2.67.2.170728-10
    depends_on:
      - php-fpm
    environment:
      FPM: php-fpm:9000
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  ls-data:
    image: sammousa/ls_nginx:2.67.2.170728-10
    volumes:
    - /limesurvey/upload
    command:
    - 'true'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'